CREATE TABLE estudio.CLIENTES 
(
ID_PERSONA bigint(20) NOT NULL,
TIPO varchar(255) DEFAULT NULL,
PRIMARY KEY (ID_PERSONA),
CONSTRAINT FK_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID_PERSONA)
);
