/**
 * Author:  mariano
 * Created: 04/08/2016
 */
CREATE TABLE estudio.CONCESIONARIO (
	IDCONCESIONARIO BIGINT(20) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) ,
	DIRECCION VARCHAR(50) ,
	PRIMARY KEY (IDCONCESIONARIO)
);

