CREATE TABLE estudio.VENDEDORES
(
ID_PERSONA bigint(20) NOT NULL,
FECHA_INGRESO datetime DEFAULT NULL,
LEGAJO varchar(255) DEFAULT NULL,
SUELDO double DEFAULT NULL,
PRIMARY KEY (ID_PERSONA),
CONSTRAINT FK_PERSONA2 FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID_PERSONA)
);
