CREATE TABLE estudio.VENDEDORES
(
IDPERSONA bigint(20) NOT NULL,
FECHA_INGRESO datetime DEFAULT NULL,
LEGAJO varchar(255) DEFAULT NULL,
SUELDO double DEFAULT NULL,
IDCONCESIONARIO bigint(20), 
PRIMARY KEY (IDPERSONA),
CONSTRAINT FK_PERSONA2 FOREIGN KEY (IDPERSONA) REFERENCES PERSONAS (IDPERSONA),
CONSTRAINT FK_Concesionario FOREIGN KEY (IDCONCESIONARIO) REFERENCES Concesionario (IDCONCESIONARIO)
);

