CREATE TABLE estudio.CLIENTES 
(
IDPERSONA bigint(20) NOT NULL,
TIPO varchar(255) DEFAULT NULL,
PRIMARY KEY (IDPERSONA),
CONSTRAINT FK_PERSONA FOREIGN KEY (IDPERSONA) REFERENCES PERSONAS (IDPERSONA)
);
